### ISSUE TITLE
[Question] List of events

### ISSUE THREAD

**Issue by KaKi87** [mholt/caddy-events-exec#9]
Hello,

The README uses `cert_obtained` as an example event but what other events are available ?

And specifically, what's the event for an HTTP request ?

Thanks

**Comment by mholt** [comment]
It's hard to give a proper list because each module emits their own events, and modules are pluggable. i.e. we don't control the events that are emitted.

There are some standard ones that are pretty common, especially related to TLS automation -- I'd recommend reading the logs for now, until we figure out a way to document the events.

This PR describes most of them for now, I think: https://github.com/caddyserver/caddy/pull/4912

**Comment by KaKi87** [comment]
I see no event name in the logs for a request, it's just `<date> <hostname> <process>[<pid>]: <json>` ?

Thanks

**Comment by mholt** [comment]
There's no event for HTTP requests... there are detailed access logs though. Usually people implement an HTTP handler module for custom HTTP request behavior.

**Comment by KaKi87** [comment]
My use case is server-side analytics, so I'd like to run a script every time Caddy receives a request, without proxying or alerting that request in any way.
Thanks

**Comment by mholt** [comment]
Definitely write an http handler module instead; it will perform much better!

**Comment by KaKi87** [comment]
*without proxying or alerting that request in any way*

**Comment by mholt** [comment]
Yeah. So write a handler. Don't proxy it or alter anything. (I assume you mean alter not alert)

**Comment by KaKi87** [comment]
Thanks, but I want to write that script in Bash, not Go :sweat_smile:

**Comment by mholt** [comment]
Then either read the logs in bash, or write a handler to emit an event on HTTP requests. We don't do this already because running a command on every HTTP request is not very performant and can open the door to DoS.
